### ISSUE TITLE
Could you please improve the usage example of vue3-particles pack on npm web

### ISSUE THREAD

**Issue by seechangan** [tsparticles/vue3#10]
Could you please improve the example of using vue3-particles local registration component in npm official website? Maybe I only need local use but I register the component globally, this seems a bit bad, I try local registration but there will be an error

**Comment by matteobruni** [comment]
> Could you please improve the example of using vue3-particles local registration component in npm official website? Maybe I only need local use but I register the component globally, this seems a bit bad, I try local registration but there will be an error

The `use` is a plugin, not a component. There's no local registration for plugins.
