### ISSUE TITLE
docs incomplete

### ISSUE THREAD

**Issue by rowanfuchs** [tsparticles/vue3#17]
The docs only describe that you need to install `vue3-particles` while this should also be with `tsparticles`

**Comment by matteobruni** [comment]
> The docs only describe that you need to install `vue3-particles` while this should also be with `tsparticles`

It’s not mandatory, you can install `tsparticles-slim` if you need a smaller version with less features

Related issue: https://github.com/matteobruni/tsparticles/issues/4784#issuecomment-1288171828

**Comment by rowanfuchs** [comment]
Oh thats very good to know, thank you!
