### ISSUE TITLE
Documentation Clarity for Vue/Nuxt 3.0+

### ISSUE THREAD

**Issue by emerg** [tsparticles/vue3#20]
In running though the documentation, I had experienced several errors and difficulties with setup in a vue/nuxt 3.0 app. I think it would be helpful to provide specific examples of code and a more thorough step-by-step guide on how to integrate tsParticles into a Vue/Nuxt 3.0+ app. I would be willing to help write this documentation to help provide clarity to other users of this package, but even myself have had a hard time getting the tsParticles package to work properly in my Vue/Nuxt 3.0 app. One main issue that some of the documentation lacks an explanation or context of where the certain code examples should be placed within a Vue/Nuxt app in order for everything to work properly.

**Comment by matteobruni** [comment]
Have you checked the Next 3 demo app inside this repository? https://github.com/tsparticles/vue3/tree/main/apps/nuxt3

**Comment by emerg** [comment]
Hi @matteobruni, thank you for providing that link. I don't know why I hadn't come across that earlier, but that was definitely a more thorough example that I needed to see in order to get it up and running on my nuxt app. I have it working now! I think it would be helpful to perhaps link directly to that on the main https://github.com/tsparticles/vue3/tree/main README page in the demos section and call out that it's good Nuxt specific example. I didnt notice the nuxt app example previously, so perhaps making it more "obvious" could help others. I think it would also be helpful to call out that the tsparticles package also needs to be installed as part of your step by step setup guide.

Thank you so much for your help and thank you for creating this package!

**Comment by matteobruni** [comment]
The `tsparticles` package is not mandatory as you can read here: https://github.com/matteobruni/tsparticles/issues/4784#issuecomment-1288171828

And that's also reported in the changelog of v2 release here: https://dev.to/tsparticles/tsparticles-202-is-out-breaking-changes-ahead-but-keeping-the-1x-support-for-now-f72

It's a series, these are all the changelog of all v2 versions, the same released in all the pull requests.
