### ISSUE TITLE
Error "onTouchMove" event

### ISSUE THREAD

**Issue by tuzenko-vladyslav** [tsparticles/vue3#24]
Hello! I am using Swiper JS with vue3-particles at one page and get an error on carousel swipe.
![image](https://github.com/tsparticles/vue3/assets/97455156/d3888707-8ddb-411b-a442-fd4d1208dc09)
Swiper emitting event "touchMove" 
![image](https://github.com/tsparticles/vue3/assets/97455156/ec36f042-550e-47d1-8ea7-0c9584685fcd)
but vue3-particles also using this event
![image](https://github.com/tsparticles/vue3/assets/97455156/b86dd202-f58e-43ac-ac4a-b6e6e08ce3fc)
What should I do in such a situation?

**Comment by matteobruni** [comment]
I don’t know, I’ve never used Swiper JS, and if they dispatch a standard event they need to be sure that the event is correctly formatted.
