### ISSUE TITLE
installation is unclear

### ISSUE THREAD

**Issue by 34r7h** [tsparticles/vue3#4]
after the template tag, where does the js go?

**Comment by matteobruni** [comment]
The `use(Particles)` must go where the `createApp` is, the other code must go in the script of the component.

You can see a sample here: https://github.com/tsparticles/vue3/blob/41dba6a7eeff8dfc22eccd06c7f5f7a331cc0e53/apps/vue3/src/App.vue#L2

**Comment by 34r7h** [comment]
great, ok i'll keep in mind when upgrading. Thanks much. 

I got it to work after fixing a mistake.. ```app.use(router).use(Particles);``` like you gave in the example.

where I had:
``` const app = createApp(App)
createApp(App).use(Particles);
app.use(createPinia())
app.use(router)
```
maybe that makes two instances.

**Comment by matteobruni** [comment]
The default Vue3 app comes with `app.use(router);`, that's why I appended that there.

**Comment by 34r7h** [comment]
yeah it should be there. i made an error. great work on this. i'm very thankful!
