### ISSUE TITLE
Feature request: Remove `particleInit` event listening when a component is destroyed

### ISSUE THREAD

**Issue by sreindo** [tsparticles/vue3#63]
Hello, I encountered a memory leak while using tsparticles plugin.

## Description
Switching the particle effect page, the `particleInit` event listener was repeatedly registered, which was not destroyed when the component was unmounted, and a memory leak occurred.

## Environment
*"@tsparticles/vue3"*: "^3.0.0",
*"tsparticles"*: "^3.3.0",
*"vue"*: "3.4.21",
 *Browser*: Chrome 122 

## Reproduction
I use the particle effect component in the login page, and  log in -> Log out -> Log in -> Log out.  Checking the Event Listeners and Performance monitor, I find that the number of DOM Nodes and JS Event Listeners has been increasing and cannot complete garbage collection
*
![1709187964252](https://github.com/tsparticles/vue3/assets/65061921/a0b3ecab-97a2-45a1-ab9f-faa9d8c04c70)

https://github.com/tsparticles/vue3/blob/fdd086d0eb44eee5beed4acea4937d2e580956d3/components/vue3/src/components/vue-particles.vue#L23-L29

By searching the source code I found that removeEventListener was needed, and I tested the particles vue2  in the same way, with no problem, that eventBus had been off when the component was destroyed。If possible, please fix the problem quickly, I would appreciate it, thank u

https://github.com/tsparticles/vue2/blob/6c1eae2a84d6216aefdc1886e1f84a98c2b45bda/components/vue2/src/Particles/vue-particles.vue#L57-L61

**Comment by matteobruni** [comment]
Thanks for reporting that, can you open a PR about that?

**Comment by Alhada06** [comment]
did a pr to fix this issue by adding the removeEventListener on the onUnmounted hook, reproduced the the issue in the nuxt app and tested the solution on chrome and edge.
On another note  in vue3 the eventBus  api as shown in the solution was removed and  using a global event bus for communicating between components is discouraged, but  this patten can still be achieved using an external library like mitt according to the docs.
