### ISSUE TITLE
Typo in demo (README.md)

### ISSUE THREAD

**Issue by kniazevgeny** [tsparticles/vue3#64]
Please replace `:particlesLoaded="particlesLoaded"` by `@particlesLoaded="particlesLoaded"`. The file /src/components/vue-particles.vue contains 
```
const emit = defineEmits<{
    (e: "particlesLoaded", container?: Container): void;
}>();
```
So that's definetly an emit. Otherwise it just doesn't print anything

**Comment by matteobruni** [comment]
Thanks, can you submit a PR for that?
