### ISSUE TITLE
tsparticles_vue3 / init error

### ISSUE THREAD

**Issue by vishakha99-gif** [tsparticles/vue3#78]
@tsparticles_vue3.js?v=0378f201:4997 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'init')

I'm getting this error while using this plugin

**Comment by matteobruni** [comment]
Some code would help

**Comment by vishakha99-gif** [comment]
> Some code would help

plugins/Partical.ts
import Particles from "@tsparticles/vue3";

export default defineNuxtPlugin((nuxtApp) => {
    // Doing something with nuxtApp
    nuxtApp.vueApp.use(Particles);
});
Mycomponent.vue
<vue-particles id="tsparticles" :options="options"  />

**Comment by matteobruni** [comment]
https://github.com/tsparticles/vue3/blob/main/apps/nuxt3/plugins/vue3-particles.client.ts

https://github.com/tsparticles/vue3/blob/main/apps/nuxt3/app.vue

This is the full Nuxt3 Sample: https://github.com/tsparticles/vue3/tree/main/apps/nuxt3
