### ISSUE TITLE
SSR Support

### ISSUE THREAD

**Issue by a21ns1g4ts** [tsparticles/vue3#80]
Are there any plans to add SSR (Server-Side Rendering) support to Vite?

**Comment by matteobruni** [comment]
Canvas libraries doesn't support SSR since it's a client-side only feature

**Comment by a21ns1g4ts** [comment]
I think there is a way to make it compatible. Knowing that some browser features are not rendered on the server side, but there is a way to suppress calls to those features in the implementations. Since Canvas requires browser environment and API’s to run, so we need to prevent running it in server environment
